# Generated by Django 3.2 on 2021-05-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('room_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_of_beds_left', models.IntegerField(default=100)),
                ('cost', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('vaccine_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vaccine_stock', models.IntegerField(default=100)),
                ('vaccine_cost', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=9999999999)),
                ('profession', models.CharField(max_length=100)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.accomodation')),
            ],
        ),
        migrations.CreateModel(
            name='PatFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='payment_date')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.patients')),
            ],
        ),
        migrations.CreateModel(
            name='EmpFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=10000)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CovApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_test_result', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.patients')),
                ('vaccine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.vaccines')),
            ],
        ),
    ]
