# Generated by Django 3.2 on 2021-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfinance',
            name='payment_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
