# Generated by Django 3.2 on 2021-05-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0002_patfinance_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('reason_for_leave', models.CharField(max_length=1000)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.employee')),
            ],
        ),
    ]
