# Generated by Django 3.2 on 2021-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(default='password', max_length=1000),
            preserve_default=False,
        ),
    ]
