# Generated by Django 3.2 on 2021-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0004_patients_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
