# Generated by Django 3.2 on 2021-05-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0005_alter_patients_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='password',
            new_name='pw',
        ),
        migrations.AddField(
            model_name='employee',
            name='pw',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
