# Generated by Django 3.2 on 2021-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0006_auto_20210528_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='pw',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='patfinance',
            name='date',
            field=models.DateField(verbose_name='payment_date'),
        ),
    ]
