# Generated by Django 3.2 on 2021-06-07 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0007_auto_20210530_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
