# Generated by Django 3.2 on 2021-06-13 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0008_auto_20210607_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 16, 47, 32, 379225, tzinfo=utc), verbose_name='Last Login'),
        ),
    ]
