# Generated by Django 3.2 on 2021-06-16 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0009_auto_20210613_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 14, 52, 14, 499557, tzinfo=utc), verbose_name='Last Login'),
        ),
    ]
