# Generated by Django 3.2 on 2021-06-19 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0010_alter_patients_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfinance',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 19, 42, 52, 669276, tzinfo=utc), verbose_name='Last Login'),
        ),
    ]
